INCLUDES += \
	-I/local/include

VENDORS := $(shell find $(VNDDIR) -maxdepth 3 -type d -name include)
INCLUDES := $(INCLUDES) $(patsubst $(VNDDIR)/%,-I$(VNDDIR)/%,$(VENDORS))

LDIR += \
	-L/local/lib

VENDORS := $(shell find $(VNDDIR) -maxdepth 3 -type d -name "lib*")
LDIR += $(patsubst $(VNDDIR)/%,-L$(VNDDIR)/%,$(VENDORS))

LFLAGS += -mwindows -mconsole

ifeq ($(MAKECMDGOALS),release)
	LFLAGS += -mconsole
endif

PROGRAM := $(PROGRAM).exe