#pragma once

#include "../rn.hpp"

#include <string>

#define KEY_SPACE         ngn::key::codeSpace
#define KEY_APOSTROPHE    ngn::key::codeApostrophe
#define KEY_COMMA         ngn::key::codeComma
#define KEY_MINUS         ngn::key::codeMinus
#define KEY_PERIOD        ngn::key::codePeriod
#define KEY_SLASH         ngn::key::codeSlash
#define KEY_0             ngn::key::code0
#define KEY_1             ngn::key::code1
#define KEY_2             ngn::key::code2
#define KEY_3             ngn::key::code3
#define KEY_4             ngn::key::code4
#define KEY_5             ngn::key::code5
#define KEY_6             ngn::key::code6
#define KEY_7             ngn::key::code7
#define KEY_8             ngn::key::code8
#define KEY_9             ngn::key::code9
#define KEY_SEMICOLON     ngn::key::codeSemicolon
#define KEY_EQUAL         ngn::key::codeEqual
#define KEY_A             ngn::key::codeA
#define KEY_B             ngn::key::codeB
#define KEY_C             ngn::key::codeC
#define KEY_D             ngn::key::codeD
#define KEY_E             ngn::key::codeE
#define KEY_F             ngn::key::codeF
#define KEY_G             ngn::key::codeG
#define KEY_H             ngn::key::codeH
#define KEY_I             ngn::key::codeI
#define KEY_J             ngn::key::codeJ
#define KEY_K             ngn::key::codeK
#define KEY_L             ngn::key::codeL
#define KEY_M             ngn::key::codeM
#define KEY_N             ngn::key::codeN
#define KEY_O             ngn::key::codeO
#define KEY_P             ngn::key::codeP
#define KEY_Q             ngn::key::codeQ
#define KEY_R             ngn::key::codeR
#define KEY_S             ngn::key::codeS
#define KEY_T             ngn::key::codeT
#define KEY_U             ngn::key::codeU
#define KEY_V             ngn::key::codeV
#define KEY_W             ngn::key::codeW
#define KEY_X             ngn::key::codeX
#define KEY_Y             ngn::key::codeY
#define KEY_Z             ngn::key::codeZ
#define KEY_LBRACKET      ngn::key::codeLBracket
#define KEY_BACKSLASH     ngn::key::codeBackslash
#define KEY_RBRACKET      ngn::key::codeRBracket
#define KEY_GRAVE_ACCENT  ngn::key::codeGraveAccent
#define KEY_WORLD_1       ngn::key::codeWorld1
#define KEY_WORLD_2       ngn::key::codeWorld2
#define KEY_ESCAPE        ngn::key::codeEscape
#define KEY_ENTER         ngn::key::codeEnter
#define KEY_TAB           ngn::key::codeTab
#define KEY_BACKSPACE     ngn::key::codeBackspace
#define KEY_INSERT        ngn::key::codeInsert
#define KEY_DELETE        ngn::key::codeDelete
#define KEY_RIGHT         ngn::key::codeRight
#define KEY_LEFT          ngn::key::codeLeft
#define KEY_DOWN          ngn::key::codeDown
#define KEY_UP            ngn::key::codeUp
#define KEY_PAGE_UP       ngn::key::codePageUp
#define KEY_PAGE_DOWN     ngn::key::codePageDown
#define KEY_HOME          ngn::key::codeHome
#define KEY_END           ngn::key::codeEnd
#define KEY_CAPS_LOCK     ngn::key::codeCapsLock
#define KEY_SCROLL_LOCK   ngn::key::codeScrollLock
#define KEY_NUM_LOCK      ngn::key::codeNumLock
#define KEY_PRINT_SCREEN  ngn::key::codePrintScreen
#define KEY_PAUSE         ngn::key::codePause
#define KEY_F1            ngn::key::codeF1
#define KEY_F2            ngn::key::codeF2
#define KEY_F3            ngn::key::codeF3
#define KEY_F4            ngn::key::codeF4
#define KEY_F5            ngn::key::codeF5
#define KEY_F6            ngn::key::codeF6
#define KEY_F7            ngn::key::codeF7
#define KEY_F8            ngn::key::codeF8
#define KEY_F9            ngn::key::codeF9
#define KEY_F10           ngn::key::codeF10
#define KEY_F11           ngn::key::codeF11
#define KEY_F12           ngn::key::codeF12
#define KEY_F13           ngn::key::codeF13
#define KEY_F14           ngn::key::codeF14
#define KEY_F15           ngn::key::codeF15
#define KEY_F16           ngn::key::codeF16
#define KEY_F17           ngn::key::codeF17
#define KEY_F18           ngn::key::codeF18
#define KEY_F19           ngn::key::codeF19
#define KEY_F20           ngn::key::codeF20
#define KEY_F21           ngn::key::codeF21
#define KEY_F22           ngn::key::codeF22
#define KEY_F23           ngn::key::codeF23
#define KEY_F24           ngn::key::codeF24
#define KEY_F25           ngn::key::codeF25
#define KEY_KP_0          ngn::key::codeKp0
#define KEY_KP_1          ngn::key::codeKp1
#define KEY_KP_2          ngn::key::codeKp2
#define KEY_KP_3          ngn::key::codeKp3
#define KEY_KP_4          ngn::key::codeKp4
#define KEY_KP_5          ngn::key::codeKp5
#define KEY_KP_6          ngn::key::codeKp6
#define KEY_KP_7          ngn::key::codeKp7
#define KEY_KP_8          ngn::key::codeKp8
#define KEY_KP_9          ngn::key::codeKp9
#define KEY_KP_DECIMAL    ngn::key::codeKpDecimal
#define KEY_KP_DIVIDE     ngn::key::codeKpDivide
#define KEY_KP_MULTIPLY   ngn::key::codeKpMultiply
#define KEY_KP_SUBTRACT   ngn::key::codeKpSubtract
#define KEY_KP_ADD        ngn::key::codeKpAdd
#define KEY_KP_ENTER      ngn::key::codeKpEnter
#define KEY_KP_EQUAL      ngn::key::codeKpEqual
#define KEY_LSHIFT        ngn::key::codeLshift
#define KEY_CTRL          ngn::key::codeCtrl
#define KEY_LCTRL         ngn::key::codeLctrl
#define KEY_LALT          ngn::key::codeLalt
#define KEY_LSUPER        ngn::key::codeLsuper
#define KEY_RSHIFT        ngn::key::codeRshift
#define KEY_RCTRL         ngn::key::codeRctrl
#define KEY_RALT          ngn::key::codeRalt
#define KEY_RSUPER        ngn::key::codeRsuper
#define KEY_MENU          ngn::key::codeMenu
#define KEY_LAST          ngn::key::codeLast

namespace ngn
{

namespace key
{
void init();

bool hit(size_t key);
bool pressed(size_t key);
bool wasPressed(size_t key);

size_t getKey(std::string key);

void update();

extern int codeSpace;
extern int codeApostrophe;
extern int codeComma;
extern int codeMinus;
extern int codePeriod;
extern int codeSlash;
extern int code0;
extern int code1;
extern int code2;
extern int code3;
extern int code4;
extern int code5;
extern int code6;
extern int code7;
extern int code8;
extern int code9;
extern int codeSemicolon;
extern int codeEqual;
extern int codeA;
extern int codeB;
extern int codeC;
extern int codeD;
extern int codeE;
extern int codeF;
extern int codeG;
extern int codeH;
extern int codeI;
extern int codeJ;
extern int codeK;
extern int codeL;
extern int codeM;
extern int codeN;
extern int codeO;
extern int codeP;
extern int codeQ;
extern int codeR;
extern int codeS;
extern int codeT;
extern int codeU;
extern int codeV;
extern int codeW;
extern int codeX;
extern int codeY;
extern int codeZ;
extern int codeLBracket;
extern int codeBackslash;
extern int codeRBracket;
extern int codeGraveAccent;
extern int codeWorld1;
extern int codeWorld2;
extern int codeEscape;
extern int codeEnter;
extern int codeTab;
extern int codeBackspace;
extern int codeInsert;
extern int codeDelete;
extern int codeRight;
extern int codeLeft;
extern int codeDown;
extern int codeUp;
extern int codePageUp;
extern int codePageDown;
extern int codeHome;
extern int codeEnd;
extern int codeCapsLock;
extern int codeScrollLock;
extern int codeNumLock;
extern int codePrintScreen;
extern int codePause;
extern int codeF1;
extern int codeF2;
extern int codeF3;
extern int codeF4;
extern int codeF5;
extern int codeF6;
extern int codeF7;
extern int codeF8;
extern int codeF9;
extern int codeF10;
extern int codeF11;
extern int codeF12;
extern int codeF13;
extern int codeF14;
extern int codeF15;
extern int codeF16;
extern int codeF17;
extern int codeF18;
extern int codeF19;
extern int codeF20;
extern int codeF21;
extern int codeF22;
extern int codeF23;
extern int codeF24;
extern int codeF25;
extern int codeKp0;
extern int codeKp1;
extern int codeKp2;
extern int codeKp3;
extern int codeKp4;
extern int codeKp5;
extern int codeKp6;
extern int codeKp7;
extern int codeKp8;
extern int codeKp9;
extern int codeKpDecimal;
extern int codeKpDivide;
extern int codeKpMultiply;
extern int codeKpSubtract;
extern int codeKpAdd;
extern int codeKpEnter;
extern int codeKpEqual;
extern int codeLshift;
extern int codeCtrl;
extern int codeLctrl;
extern int codeLalt;
extern int codeLsuper;
extern int codeRshift;
extern int codeRctrl;
extern int codeRalt;
extern int codeRsuper;
extern int codeMenu;
extern int codeLast;

} // key

} // ngn